### ISSUE TITLE
How do you set this up with Cmake?

### ISSUE THREAD

**Issue by moonshineTheleocat** [gscept/nebula-trifid#3]
I am trying to get this set up with CMake, and compile, however I can't figure out exactly what everything is or how to properly set it up.

I tried looking for a bit of documentation on this, but this seems to have not been done just yet.
I have downloaded all the neccessary libraries so far... but there are a few I don't recognize.

something about CG
I can't figure out how to set up cmake with GLEW
There are some dependents from Maya, but I can't find any information on that.

**Comment by kaffeewolf** [comment]
What kinds of errors are you getting, and what platform/compilers are you using? there is some very basic information [here](http://nebulatrifid.org/documentation/other-documentation/development/setting-up-the-development-environment/) that you may want to look at. There is currently no demoproject, so its a bit hard to get started, but we will put up something very soon.

**Comment by moonshineTheleocat** [comment]
I managed to fix most of my problems. But, for some reason CMake can not -

Find GLEW, though it's located inside the extlibs folder
and it can not locate Maya, which Maya 2014 is installed on the system.
I also don't know what the OpenMaya stuff are.

**Comment by moonshineTheleocat** [comment]
Also... I'm able to complete the configuration. But it seems that there are some problems in compiling.

http://i.imgur.com/SFVQQTl.png

**Comment by kaffeewolf** [comment]
We are not using Maya for anything at the moment.
There a bunch of libraries that are checked for in cmake that are not used (anymore), and some submodules add their own checks that are not necessarily fatal if they fail. As long as CMake doesnt abort you are good to go. I assume you enabled the Maya plugin in CMake? It is deprecated, all content import is done via FBX files.
The compile errors you are getting seem to be related to it not being able to compile the .nidl files to code. Try explicitely compiling the different _NIDL projects (foundation_NIDL, application_NIDL) and see what happens there. Did you change any default settings in cmake with the N_ prefix?

**Comment by moonshineTheleocat** [comment]
Not that I am aware of.

**Comment by kaffeewolf** [comment]
Then it should just work, can you post a full output of the compilation? Not just the error list?

**Comment by moonshineTheleocat** [comment]
I built everything from NIDL in VS, but it didn't run through the process. It looks like the Compiler was able to go over each one of them just fine.

**Comment by moonshineTheleocat** [comment]
Here's the Compile output
http://pastebin.com/7bfFBY1m
Here is the Error List
http://i.imgur.com/ZEqgLjU.png

**Comment by kaffeewolf** [comment]
Ah, that was my bad, I did some porting to linux and messed up some cmake settings, try pulling and updating submodules again.

**Comment by moonshineTheleocat** [comment]
Still No good.
ALL_BUILD output
http://pastebin.com/Z2jrT6YM
Error Output
http://pastebin.com/KVFEjZg5

Also... should I go ahead and remove Basegameattributes.h? The header file does not exist, and it causes .cc file to fail on compile.

See error 217

**Comment by moonshineTheleocat** [comment]
It looks like that for some reason, it's mixing Debug and Release DLLs.

**Comment by kaffeewolf** [comment]
It looks like your version of Qt (most likely) is built with the Multi-threaded DLL instead of Multi-threaded runtime. Apart from that some library that you are trying to link with is built with Visual Studio 2010, and you are using Visual Studio 2013. I would suspect you will have to compile your own version of Qt4 with  VS2013 with correct runtimes.

**Comment by moonshineTheleocat** [comment]
Next error has something to do with a Runtime mismatch or something. I don't know how to go about fixing this, because I have no idea what you guys were doing.

Warnings
http://pastebin.com/NWzvJEZY

Output
http://pastebin.com/RwKWsk4V

Is there something I am missing? This is a release build. I'll try a Debug

**Comment by moonshineTheleocat** [comment]
Debug seems to break some code

Errors
http://pastebin.com/WRFqE7cj

Output
http://pastebin.com/GzGxPEr9

**Comment by moonshineTheleocat** [comment]
What version of VS is this compiled under? I'll install that version and give it a try and see if I can get any results

**Comment by MS-Astra** [comment]
> Apart from that some library that you are trying to link with is built with **Visual Studio 2010**...

**Comment by kaffeewolf** [comment]
Indeed, as MS-Astra already mentioned, you are mixing libraries compiled with/for different versions of visual studio. I still suspect it's your version of Qt.

**Comment by moonshineTheleocat** [comment]
I've picked up a 2013 x86 version of QT when I compiled that.

**Comment by moonshineTheleocat** [comment]
I think I figured out what's going wrong. The build process for QT is set up for MD. Which is causing the whole linking error. I'm going to see what happens when I compile it with MT

**Comment by moonshineTheleocat** [comment]
I think I found the issue.

QT is set up for Static Linking for all vsMVC builds. I am going to see what happens when I change that.
In file mkspecs/win32-msvc2013/qmake.conf
I change this:
QMAKE_CFLAGS_RELEASE    = -O2 -MD

To this:
QMAKE_CFLAGS_RELEASE    = -O2 -MT

**Comment by moonshineTheleocat** [comment]
_sigh_ trade one villain for another. So. It looks like the problem was with Qmakes config. Now I got some even more annoying problems. I have never seen these a MSB6006 error before, and I am guessing it has something to do with Qt still.

Output
http://pastebin.com/37HM3krY

Error
http://pastebin.com/nncsi88Z

Never mind, back to problem 1

**Comment by moonshineTheleocat** [comment]
Good news! I have solved the most foremost of problems! But there are still some compiler errors I don't quite know where to begin to fix.

For problems with QT, I had to build a config for it first, and then open up the solution in Visual Studios. For EACH and Every single project in QT, I had to change it's Code Generation property from /MD, to /MT.

I'm willing to guess that for all other problems alike this, will need the same solution.

now we still have linking problems, and this is caused by repeating bits of code?

Before changing NV stuff to /MT. Excluded warnings
http://pastebin.com/8JWL8S0P

After changing NV stuff to /MT. Only 7 errors. Warnings included for extra information. LNKER mismatch problems fixed!
http://pastebin.com/9sKcwUh6

Output
http://pastebin.com/CsPZS1eF

Other notes. Basegameattributes.h exists AFTER qtnebulawidget.cc has been attempted at compile. I am guessing there is an order problem?

**Comment by moonshineTheleocat** [comment]
Code completely compiles! Now having problems trying to run.
Am I supposed to make an installer for this to run? Or something else?
http://i.imgur.com/KDf80uu.png

FMOD studios is installed, so is the API segment for it. I tried copying a FMOD.dll into sysWOW64, but that didn't work.

**Comment by moonshineTheleocat** [comment]
Alright. Had to copy DLLS directly into bin folder.
