### ISSUE TITLE
Batcher failing in two Segments.

### ISSUE THREAD

**Issue by moonshineTheleocat** [gscept/nebula-trifid#4]
The batcher is failing in three parts. The first part, it looks like something is wrong with a file.

The grid model exists... it's just not being read.
http://pastebin.com/re0k0KwK

And then something is going wrong with the textures, and I'm not quite sure what.
[ERROR] ProjectInfo: attr 'TextureAttrTable' does not exist for platform 'win32' in projectinfo.xml!

I looked into the projectinfo.xml folder, and didn't see the field. So do I need to create that?

Then finally... something causes gamebatcher to fail.
Found globals.xml, exporting...
---- Done exporting global attributes ----

Not much information on this in the log.

And attempting to run level editor triggers message....
http://i.imgur.com/RoGC2Kh.png

**Comment by kaffeewolf** [comment]
you are missing a proper project, the files in the git repo are only the sdk and default textures/meshes, so you wont be able to even start it (as you noticed). I'm currently away from my development machine, but I can hook you up tomorrow with a simple demo project.

**Comment by moonshineTheleocat** [comment]
That will be great. Thank you!

**Comment by kaffeewolf** [comment]
I added a new submodule called nebula-demos. The demos are a bit random, but its a starting point at least. You should be able to follow the setup as explained here: http://nebulatrifid.org/documentation/manual/installation-and-projects/

**Comment by Richardds** [comment]
Hello, i have problem with "ProjectInfo: attr 'TextureAttrTable'" as well. I followed Installation and Projects documentation but i got assertion. I compiled Demo project but texture is missing because of "ProjectInfo: attr 'TextureAttrTable'" Screen: http://prntscr.com/7fjkxe

**Comment by Richardds** [comment]
I can't run NebulaDemoApplication because nebula-demo doesn't inlude "static.db4" database. http://prntscr.com/7fru55 And I can't run Level Editor as well http://prntscr.com/7frxns

**Comment by kaffeewolf** [comment]
Richard, the static.db4 is generated by the batchexporter, you will have to setup your project as described in the link earlier. In the batchexporter menu set the toolkit dir to the root of the git checkout and the working directory to the project you are working with, in this case nebula-demos. After that select all the different batchers in the batchexporter and then run export. 
After that it should be possible to start the leveleditor

**Comment by Richardds** [comment]
Firstly fbxbatcher fail but after i set Parallel Jobs to 8 it success, Thanks

**Comment by moonshineTheleocat** [comment]
I'm not getting any errors from the Batcher's log file.

But the editor still does not want to load. Currently it's having problems locate placeholder.dds.

http://i.imgur.com/MOEaMUC.png

**Comment by kaffeewolf** [comment]
It looks like your working directory is not correct, placeholder is one of the first textures it tries to load. Did you setup the toolkit directory and work directory and ran all the batchers afterwards?

**Comment by moonshineTheleocat** [comment]
The tookit directory was set to /trunk/ which is the folder above all the code, and the bin folder. Bascally containing code, bin, data, work, ect.

I ran the batcher, and it seems to have gone through without any errors. It didn't tell me if there was one.

**Comment by kaffeewolf** [comment]
did you set the working directory as well? it should point to the projects/nebula-demos folder

**Comment by kaffeewolf** [comment]
I guess you figured it out or moved on, I'm closing this issue ;)
